import {Book} from "./book.model";

export const BookDummys: Book[] = [
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfd', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfd', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfd', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfd', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfd', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfd', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfd', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfd', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},
  {id: 0, author: 'dfdf', title: 'dfdf', page_count: 0, categories: [{id: 0, genre_name: ''}, {id: 0, genre_name: ''}], img: 'assets/img/books/acotar_1.jpeg'},

]
